baseURL = "https://cahiersdusocialisme.fr/"
languageCode = "fr"
defaultContentLanguage = "fr"
title = "Les Cahiers du Socialisme"

[params]
  description = "Théorie et pensée socialiste"
  subtitle = "Revue d'idées et de réflexion politique"
  mainSections = ["posts"]

[taxonomies]
  category = "categories"
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Articles"
    url = "/posts/"
    weight = 5

  [[menu.main]]
    name = "Qui sommes-nous"
    url = "/page/qui-sommes-nous/"
    weight = 10
