baseURL = "https://cahiersdusocialisme.fr/"
languageCode = "fr"
defaultContentLanguage = "fr"
title = "Les Cahiers du Socialisme"

[params]
  description = "Théorie et pensée socialiste"
  subtitle = "Revue d'idées et de réflexion politique"

[taxonomies]
  category = "categories"
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS"]
